build-job:
  stage: build
  artifacts:
     paths:
       - ./int-lenet
       - ./float-lenet
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - make

test-job1:
  stage: test
  script:
    - echo "Testing ..."
    - { for i in {0..9999}; do x=$(./int-lenet $i|cut -d" " -f 3); y=$(./float-lenet $i|cut -d" " -f 3); if test $x -ne $y; then echo $i; fi; done } > delta
    - diff delta differences
